# Generated by Django 4.2.6 on 2024-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummers_app', '0002_drummerphoto_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drummerphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drummer_photos/'),
        ),
    ]
