# Generated by Django 4.2.13 on 2025-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drummers", "0001_initial"),
        ("discography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="drummers",
            field=models.ManyToManyField(
                blank=True, related_name="tracks_played", to="drummers.drummer"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="collaborating_drummers",
            field=models.ManyToManyField(
                blank=True,
                related_name="artists_collaborating_with_drummer",
                to="drummers.drummer",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="albums_featured", to="discography.artist"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="drummers",
            field=models.ManyToManyField(
                blank=True, related_name="albums_played", to="drummers.drummer"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="albums", to="discography.track"
            ),
        ),
    ]
