# Generated by Django 4.2.13 on 2024-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography_app", "0004_alter_artist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="album_cover",
            field=models.ImageField(default="", upload_to="album_covers/"),
            preserve_default=False,
        ),
    ]
