services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drumlib_web_local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: drumlib_db_local
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - DrumLibDBVolume:/var/lib/postgresql/data

volumes:
  DrumLibDBVolume:
  static_volume:
  media_volume:
