version: '3'

services:

  web:
    image: python:3.8
    command: bash -c "pip install -r /code/requirements.txt && sleep infinity"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
      image: postgres:13
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
