version: '3'

services:

  web:
    image: python:3.8
    command: bash -c "apt-get update && apt-get install -y graphviz libgraphviz-dev && pip install -r /code/requirements.txt && python /code/DrumLib/manage.py migrate && python /code/DrumLib/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
      image: postgres:13
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - DrumLibDBVolume:/var/lib/postgresql/data

volumes:
  DrumLibDBVolume: