version: '3'

services:

  web:
    image: mlhost81/drumlib:latest
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python /app/DrumLib/manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - DrumLibDBVolume:/var/lib/postgresql/data

volumes:
  DrumLibDBVolume:
