# Generated by Django 4.2.13 on 2025-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('collaborating_artists', models.ManyToManyField(blank=True, related_name='drummers_collaborating_with_artist', to='discography.artist')),
            ],
        ),
        migrations.CreateModel(
            name='DrummerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drummer_photos/')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('image_author', models.CharField(blank=True, max_length=255, null=True)),
                ('drummers', models.ManyToManyField(blank=True, related_name='photos_of_drummer', to='drummers.drummer')),
            ],
        ),
        migrations.AddField(
            model_name='drummer',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='drummers_on_photo', to='drummers.drummerphoto'),
        ),
    ]
