# Generated by Django 4.2.6 on 2024-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drummers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drummerphoto",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
