# Generated by Django 4.2.13 on 2024-08-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="track",
        ),
    ]
